### ISSUE TITLE
"# Change Log" title gets inserted on every release

### ISSUE THREAD

**Issue by ffxsam** [conventional-changelog/standard-version#305]
Despite following the instructions in the README, I get multiple titles inserted in my `CHANGELOG.md` file:

```md
# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

# [0.2.0](https://github.com/ffxsam/xx/compare/v0.1.0...v0.2.0) (2019-02-19)


### Features

* **pirates:** Added the pirates ([929c0af](https://github.com/ffxsam/xx/commit/929c0af))



# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

# 0.1.0 (2019-02-18)
```

**Comment by jbadan** [comment]
I am experiencing the same issue when using the `infile` option

![screen shot 2019-02-19 at 2 36 32 pm](https://user-images.githubusercontent.com/29607818/53045889-9d6b0300-3443-11e9-84fa-42b688fcca19.png)

**Comment by jthomerson** [comment]
As noted in the related PR #307, it appears that this issue was fixed by b684c784c8986226889feb1524bc029b913c9571 in #292, so this issue could be closed.

**Comment by sobolevn** [comment]
Nope, this is still happening. Here's the reproduction: https://github.com/wemake-services/kira-release

I am using `5.0.2`

**Comment by sobolevn** [comment]
Btw, this happens with Gitlab (not sure about other platforms):
<img width="1205" alt="Снимок экрана 2019-04-02 в 22 21 12" src="https://user-images.githubusercontent.com/4660275/55430033-afd57200-5595-11e9-8acf-e24ee84da318.png">

**Comment by abcfy2** [comment]
Same here. Hope this issue could be fixed soon. :)
